version: '2'

services:

  keycloak:
    image: jboss/keycloak:3.4.3.Final
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8081:8080

  clarksnut:
      image: clarksnut/clarksnut:1.2.0.RC3
      environment:
        - "-Dswarm.project.stage=peru"
      ports:
        - 8080:8080

  clarksnut-mail-collector:
      image: clarksnut/clarksnut-mail-collector:latest
      ports:
        - 8180:8080
