version: '2'

services:

  keycloak:
    image: jboss/keycloak:3.4.3.Final
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8081:8080
    networks:
      - sso

  clarksnut:
      image: clarksnut/keycloak:3.4.3.Final
      environment:
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
      ports:
        - 8081:8080
      networks:
        - sso
